export const CONST = {
  DB: {
    INFO: 'INFO',
    ORGANIZATION: 'ORGANIZATION',
    ORGANIZATION_INFO: 'ORGANIZATION_INFO',
    USER: 'USER',
    USER_INFO: 'USER_INFO',
    INDEXS: {
      ORGANIZATION_PRIORITY_ORDER: 'ORGANIZATION_PRIORITY_ORDER',
      ORGANIZATION_PARENT: 'ORGANIZATION_PARENT',
      ORGANIZATION_USER: 'ORGANIZATION_USER',
      SK_TIME: 'SK_TIME',
    },
  },
};
